services:
  - type: web
    name: zaiko-app
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
